// PROBLEM #2 - Even Fibonacci Numbers

// QUESTION: 
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

// ANSWER: 
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms..

function makeFibonacci(num) {
  const sequence = [1, 2]; // Initialize the sequence with the first two Fibonacci numbers
  for (let i = 2; i <= num; i++) {
    sequence[i] = sequence[i - 1] + sequence[i - 2]; // Generate the next Fibonacci number
  }
  return sequence;
}

function fibonacciDiff(num) {
  const diffSequence = makeFibonacci(num);
  const diffArray= [];

  for (let i = 2; i <= num; i++) {
    const difference = diffSequence[i] - diffSequence[i - 1];
    diffArray.push(difference);
  }

  return diffArray;
}

const n = 1000;
const fibonacciDifferences = fibonacciDiff(num);

console.log(fibonacciDifferences); // An array containing the differences between consecutive Fibonacci numbers up to the 1000th number